-- Populate SEO settings for JJP Solutions pages
INSERT INTO public.seo_settings (page_path, title, description, keywords, robots, canonical_url, og_title, og_description, twitter_title, twitter_description) VALUES
('/', 'JJP Solutions - Professional Business Dashboard', 'Advanced business management platform for streamlined operations, secure communications, and intelligent analytics.', ARRAY['business dashboard', 'admin panel', 'JJP Solutions', 'enterprise management', 'secure communications'], 'index, follow', '/', 'JJP Solutions - Professional Business Dashboard', 'Advanced business management platform for streamlined operations, secure communications, and intelligent analytics.', 'JJP Solutions - Professional Business Dashboard', 'Advanced business management platform for streamlined operations, secure communications, and intelligent analytics.'),

('/auth', 'Secure Login - JJP Solutions', 'Secure authentication portal for JJP Solutions business management platform. Access your dashboard with enterprise-grade security.', ARRAY['secure login', 'business authentication', 'JJP Solutions login', 'enterprise security'], 'noindex, follow', '/auth', 'Secure Login - JJP Solutions', 'Secure authentication portal for JJP Solutions business management platform.', 'Secure Login - JJP Solutions', 'Secure authentication portal for JJP Solutions business management platform.'),

('/dashboard', 'Dashboard - JJP Solutions', 'Comprehensive business intelligence dashboard with real-time analytics, secure communications, and operational insights.', ARRAY['business dashboard', 'analytics', 'business intelligence', 'JJP Solutions dashboard'], 'noindex, follow', '/dashboard', 'Business Dashboard - JJP Solutions', 'Comprehensive business intelligence dashboard with real-time analytics and insights.', 'Business Dashboard - JJP Solutions', 'Comprehensive business intelligence dashboard with real-time analytics and insights.'),

('/dashboard/admin', 'Admin Panel - JJP Solutions', 'Administrative control panel for user management, system configuration, and security monitoring.', ARRAY['admin panel', 'user management', 'system administration', 'JJP Solutions admin'], 'noindex, follow', '/dashboard/admin', 'Admin Panel - JJP Solutions', 'Administrative control panel for comprehensive system management.', 'Admin Panel - JJP Solutions', 'Administrative control panel for comprehensive system management.'),

('/dashboard/messages', 'Secure Messaging - JJP Solutions', 'Enterprise-grade secure messaging system with real-time communication and file sharing capabilities.', ARRAY['secure messaging', 'business communication', 'enterprise messaging', 'JJP Solutions messages'], 'noindex, follow', '/dashboard/messages', 'Secure Messaging - JJP Solutions', 'Enterprise-grade secure messaging system for business communications.', 'Secure Messaging - JJP Solutions', 'Enterprise-grade secure messaging system for business communications.'),

('/dashboard/analytics', 'Business Analytics - JJP Solutions', 'Advanced analytics and reporting tools for data-driven business insights and performance monitoring.', ARRAY['business analytics', 'reporting tools', 'data insights', 'performance monitoring'], 'noindex, follow', '/dashboard/analytics', 'Business Analytics - JJP Solutions', 'Advanced analytics and reporting tools for data-driven business insights.', 'Business Analytics - JJP Solutions', 'Advanced analytics and reporting tools for data-driven business insights.'),

('/dashboard/news', 'News Intelligence - JJP Solutions', 'AI-powered news aggregation and analysis for industry insights and market intelligence.', ARRAY['news intelligence', 'market analysis', 'industry insights', 'AI news'], 'noindex, follow', '/dashboard/news', 'News Intelligence - JJP Solutions', 'AI-powered news aggregation and analysis for industry insights.', 'News Intelligence - JJP Solutions', 'AI-powered news aggregation and analysis for industry insights.');