// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khpxxilvraavgartihvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtocHh4aWx2cmFhdmdhcnRpaHZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzQ1MDQsImV4cCI6MjA2NzYxMDUwNH0.ovqvMBxI86Ao0yEHWhi6CYKVTZsKxL-Sdl737mDhDMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});